[theme]
background = "#1D2021"
primary = "#D65D0E"
secondary = "#8F3F71"
title = "#9D0006"
playing = "#076678"
playing_selected = "#8F3F71"
playing_bg = "#1D2021"
highlight = "#9D0006"
highlight_bg = "#B8BB26"
error = "#FFFFFF"
error_bg = "#9D0006"
statusbar = "#1D2021"
statusbar_progress = "#9D0006"
statusbar_bg = "#8F3F71"
cmdline = "#8EC07C"
cmdline_bg = "#1D2021"
search_match = "#D65D0E"

# "#9D0006"
# "#B8BB26"
# "#1D2021" 
# "#D65D0E"
# "#8F3F71"
# "#B57614"
# "#076678"
# "#8EC07C" 
